version: '3.8'
services:
  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    volumes:
      - /var/log/shareit/gateway
    ports:
      - "8080:8080"
      - "5006:5006"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090


  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    volumes:
      - /var/log/shareit/server
    ports:
      - "9090:9090"
      - "5005:5005"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USER=root
      - SPRING_DATASOURCE_PASSWORD=root


  db:
    image: postgres:13.7-alpine
    container_name: db
    command: [ "postgres", "-c", "log_statement=all", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgres" ]
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./logs:/var/log/postgres
    ports:
      - "6541:5432"
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  db_data: